# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adocao.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'adocao.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x64ocao.proto\x12\x06\x61\x64ocao\"\x15\n\x13ListaAnimaisRequest\"7\n\x14ListaAnimaisResponse\x12\x1f\n\x07\x61nimais\x18\x01 \x03(\x0b\x32\x0e.adocao.Animal\"+\n\x16VerificarAnimalRequest\x12\x11\n\tanimal_id\x18\x01 \x01(\x05\"M\n\x17VerificarAnimalResponse\x12\x1e\n\x06\x61nimal\x18\x01 \x01(\x0b\x32\x0e.adocao.Animal\x12\x12\n\ndisponivel\x18\x02 \x01(\x08\"B\n\x06\x41nimal\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07\x65specie\x18\x03 \x01(\t\x12\r\n\x05idade\x18\x04 \x01(\x05\"B\n\x16SolicitarAdocaoRequest\x12\x11\n\tanimal_id\x18\x01 \x01(\x05\x12\x15\n\rnome_adotante\x18\x02 \x01(\t\"<\n\x17SolicitarAdocaoResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2\x8e\x02\n\rAnimalService\x12U\n\x18ListarAnimaisDisponiveis\x12\x1b.adocao.ListaAnimaisRequest\x1a\x1c.adocao.ListaAnimaisResponse\x12R\n\x0fVerificarAnimal\x12\x1e.adocao.VerificarAnimalRequest\x1a\x1f.adocao.VerificarAnimalResponse\x12R\n\x0fSolicitarAdocao\x12\x1e.adocao.SolicitarAdocaoRequest\x1a\x1f.adocao.SolicitarAdocaoResponse2c\n\rAdocaoService\x12R\n\x0fSolicitarAdocao\x12\x1e.adocao.SolicitarAdocaoRequest\x1a\x1f.adocao.SolicitarAdocaoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adocao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTAANIMAISREQUEST']._serialized_start=24
  _globals['_LISTAANIMAISREQUEST']._serialized_end=45
  _globals['_LISTAANIMAISRESPONSE']._serialized_start=47
  _globals['_LISTAANIMAISRESPONSE']._serialized_end=102
  _globals['_VERIFICARANIMALREQUEST']._serialized_start=104
  _globals['_VERIFICARANIMALREQUEST']._serialized_end=147
  _globals['_VERIFICARANIMALRESPONSE']._serialized_start=149
  _globals['_VERIFICARANIMALRESPONSE']._serialized_end=226
  _globals['_ANIMAL']._serialized_start=228
  _globals['_ANIMAL']._serialized_end=294
  _globals['_SOLICITARADOCAOREQUEST']._serialized_start=296
  _globals['_SOLICITARADOCAOREQUEST']._serialized_end=362
  _globals['_SOLICITARADOCAORESPONSE']._serialized_start=364
  _globals['_SOLICITARADOCAORESPONSE']._serialized_end=424
  _globals['_ANIMALSERVICE']._serialized_start=427
  _globals['_ANIMALSERVICE']._serialized_end=697
  _globals['_ADOCAOSERVICE']._serialized_start=699
  _globals['_ADOCAOSERVICE']._serialized_end=798
# @@protoc_insertion_point(module_scope)
