# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import adocao_pb2 as adocao__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adocao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnimalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarAnimaisDisponiveis = channel.unary_unary(
                '/adocao.AnimalService/ListarAnimaisDisponiveis',
                request_serializer=adocao__pb2.ListaAnimaisRequest.SerializeToString,
                response_deserializer=adocao__pb2.ListaAnimaisResponse.FromString,
                _registered_method=True)
        self.VerificarAnimal = channel.unary_unary(
                '/adocao.AnimalService/VerificarAnimal',
                request_serializer=adocao__pb2.VerificarAnimalRequest.SerializeToString,
                response_deserializer=adocao__pb2.VerificarAnimalResponse.FromString,
                _registered_method=True)
        self.SolicitarAdocao = channel.unary_unary(
                '/adocao.AnimalService/SolicitarAdocao',
                request_serializer=adocao__pb2.SolicitarAdocaoRequest.SerializeToString,
                response_deserializer=adocao__pb2.SolicitarAdocaoResponse.FromString,
                _registered_method=True)


class AnimalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListarAnimaisDisponiveis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerificarAnimal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolicitarAdocao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnimalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarAnimaisDisponiveis': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarAnimaisDisponiveis,
                    request_deserializer=adocao__pb2.ListaAnimaisRequest.FromString,
                    response_serializer=adocao__pb2.ListaAnimaisResponse.SerializeToString,
            ),
            'VerificarAnimal': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarAnimal,
                    request_deserializer=adocao__pb2.VerificarAnimalRequest.FromString,
                    response_serializer=adocao__pb2.VerificarAnimalResponse.SerializeToString,
            ),
            'SolicitarAdocao': grpc.unary_unary_rpc_method_handler(
                    servicer.SolicitarAdocao,
                    request_deserializer=adocao__pb2.SolicitarAdocaoRequest.FromString,
                    response_serializer=adocao__pb2.SolicitarAdocaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adocao.AnimalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adocao.AnimalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnimalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarAnimaisDisponiveis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adocao.AnimalService/ListarAnimaisDisponiveis',
            adocao__pb2.ListaAnimaisRequest.SerializeToString,
            adocao__pb2.ListaAnimaisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerificarAnimal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adocao.AnimalService/VerificarAnimal',
            adocao__pb2.VerificarAnimalRequest.SerializeToString,
            adocao__pb2.VerificarAnimalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolicitarAdocao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adocao.AnimalService/SolicitarAdocao',
            adocao__pb2.SolicitarAdocaoRequest.SerializeToString,
            adocao__pb2.SolicitarAdocaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdocaoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SolicitarAdocao = channel.unary_unary(
                '/adocao.AdocaoService/SolicitarAdocao',
                request_serializer=adocao__pb2.SolicitarAdocaoRequest.SerializeToString,
                response_deserializer=adocao__pb2.SolicitarAdocaoResponse.FromString,
                _registered_method=True)


class AdocaoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SolicitarAdocao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdocaoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SolicitarAdocao': grpc.unary_unary_rpc_method_handler(
                    servicer.SolicitarAdocao,
                    request_deserializer=adocao__pb2.SolicitarAdocaoRequest.FromString,
                    response_serializer=adocao__pb2.SolicitarAdocaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adocao.AdocaoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adocao.AdocaoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdocaoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SolicitarAdocao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adocao.AdocaoService/SolicitarAdocao',
            adocao__pb2.SolicitarAdocaoRequest.SerializeToString,
            adocao__pb2.SolicitarAdocaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
