syntax = "proto3";

package adocao;

service AnimalService {

    rpc ListarAnimaisDisponiveis (ListaAnimaisRequest)
        returns (ListaAnimaisResponse);

    rpc VerificarAnimal (VerificarAnimalRequest)
        returns (VerificarAnimalResponse);

    rpc SolicitarAdocao (SolicitarAdocaoRequest)
        returns (SolicitarAdocaoResponse);
}


service AdocaoService {

    rpc SolicitarAdocao (SolicitarAdocaoRequest)
        returns (SolicitarAdocaoResponse);
}

message ListaAnimaisRequest {
}

message ListaAnimaisResponse {
    repeated Animal animais = 1;
}

message VerificarAnimalRequest {
    int32 animal_id = 1;
}

message VerificarAnimalResponse {
    Animal animal = 1;
    bool disponivel = 2;
}

message Animal {
    int32 id = 1;
    string nome = 2;
    string especie = 3;
    int32 idade = 4;
}

message SolicitarAdocaoRequest {
    int32 animal_id = 1;
    string nome_adotante = 2;
}

message SolicitarAdocaoResponse {
    bool sucesso = 1;
    string mensagem = 2;
}